spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    username: admin
    password: ${AWS_RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.c360gwm285v0.us-east-2.rds.amazonaws.com:3306/grass?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  data:
    redis:
      host: grass-redis.redis.cache.windows.net
      password: ${AZURE_REDIS_PASSWORD}
      port: 6380
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: TRUE

  logging:
    level:
      org:
        springframework:
          jdbc: DEBUG
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql: TRACE
          orm:
            jdbc:
              bind: TRACE
server:
  port: 8080

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/v1/**

cloud:
  aws:
    s3:
      bucket: grass-bucket
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: us-east-2
      auto: false
    stack:
      auto: false

jwt:
  secret-key: ${JWT_SECRET}