name: Build and deploy JAR app to Azure Web App - grass-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      contents: read
      id-token: write  

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Clear Gradle cache
        run: ./gradlew clean

      - name: Set environment variables and decode them
        run: |
          # base64로 인코딩된 시크릿 값을 디코딩 및 설정
          echo "Decoding environment variables"

          # JWT_SECRET 디코딩
          export JWT_SECRET=$(echo "${{ secrets.JWT_SECRET }}" | base64 --decode || { echo "Failed to decode JWT_SECRET"; exit 1; })
          echo "JWT_SECRET successfully decoded"

          # APP_TIMEZONE 디코딩
          export APP_TIMEZONE=$(echo "${{ secrets.APP_TIMEZONE }}" | base64 --decode || { echo "Failed to decode APP_TIMEZONE"; exit 1; })
          echo "APP_TIMEZONE successfully decoded"

          # 다른 환경 변수들도 동일하게 처리
          export AWS_RDS_PASSWORD=$(echo "${{ secrets.AWS_RDS_PASSWORD }}" | base64 --decode || { echo "Failed to decode AWS_RDS_PASSWORD"; exit 1; })
          echo "AWS_RDS_PASSWORD successfully decoded"

          export AWS_RDS_URL=$(echo "${{ secrets.AWS_RDS_URL }}" | base64 --decode || { echo "Failed to decode AWS_RDS_URL"; exit 1; })
          echo "AWS_RDS_URL successfully decoded"

          export AWS_RDS_USER=$(echo "${{ secrets.AWS_RDS_USER }}" | base64 --decode || { echo "Failed to decode AWS_RDS_USER"; exit 1; })
          echo "AWS_RDS_USER successfully decoded"

          export AZURE_REDIS_HOST=$(echo "${{ secrets.AZURE_REDIS_HOST }}" | base64 --decode || { echo "Failed to decode AZURE_REDIS_HOST"; exit 1; })
          echo "AZURE_REDIS_HOST successfully decoded"

          export AZURE_REDIS_PASSWORD=$(echo "${{ secrets.AZURE_REDIS_PASSWORD }}" | base64 --decode || { echo "Failed to decode AZURE_REDIS_PASSWORD"; exit 1; })
          echo "AZURE_REDIS_PASSWORD successfully decoded"

          export S3_ACCESS_KEY=$(echo "${{ secrets.S3_ACCESS_KEY }}" | base64 --decode || { echo "Failed to decode S3_ACCESS_KEY"; exit 1; })
          echo "S3_ACCESS_KEY successfully decoded"

          export S3_BUCKET_NAME=$(echo "${{ secrets.S3_BUCKET_NAME }}" | base64 --decode || { echo "Failed to decode S3_BUCKET_NAME"; exit 1; })
          echo "S3_BUCKET_NAME successfully decoded"

          export S3_REGION=$(echo "${{ secrets.S3_REGION }}" | base64 --decode || { echo "Failed to decode S3_REGION"; exit 1; })
          echo "S3_REGION successfully decoded"

          export S3_SECRET_KEY=$(echo "${{ secrets.S3_SECRET_KEY }}" | base64 --decode || { echo "Failed to decode S3_SECRET_KEY"; exit 1; })
          echo "S3_SECRET_KEY successfully decoded"

      - name: Print environment variables
        run: |
          # 모든 환경 변수 로그로 출력
          echo "JWT_SECRET: $JWT_SECRET"
          echo "APP_TIMEZONE: $APP_TIMEZONE"
          echo "AWS_RDS_PASSWORD: $AWS_RDS_PASSWORD"
          echo "AWS_RDS_URL: $AWS_RDS_URL"
          echo "AWS_RDS_USER: $AWS_RDS_USER"
          echo "AZURE_REDIS_HOST: $AZURE_REDIS_HOST"
          echo "AZURE_REDIS_PASSWORD: $AZURE_REDIS_PASSWORD"
          echo "AZURE_REDIS_PORT: $AZURE_REDIS_PORT"
          echo "S3_ACCESS_KEY: $S3_ACCESS_KEY"
          echo "S3_BUCKET_NAME: $S3_BUCKET_NAME"
          echo "S3_REGION: $S3_REGION"
          echo "S3_SECRET_KEY: $S3_SECRET_KEY"
          echo "SERVER_PORT: $SERVER_PORT"

      - name: Build with Gradle
        run: ./gradlew build --no-build-cache -Duser.timezone=$APP_TIMEZONE

      - name: List files in build/libs directory
        run: ls -al ${{ github.workspace }}/build/libs

      - name: Save build path for later steps
        id: build_dir
        run: |
          JAR_PATH=$(find ${{ github.workspace }}/build/libs -name '*.jar')
          echo "JAR_PATH=${JAR_PATH}" >> $GITHUB_ENV
          echo "JAR file found: ${JAR_PATH}"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_198AA26D7CA04140A103D131898ADC4F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BCA99810567249F98FC37CFA9B624D6B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8CF1A769465B43AEB7F9CDD407F60A95 }}

      - name: Verify JAR path
        run:  |
          echo "Deploying JAR from path: $JAR_PATH"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'grass-server'
          slot-name: 'Production'
          package: ${{ env.JAR_PATH }}
